layout_spectrum: 0.8275334909558296
name: MadeByJames
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
color:
  brandStrength: 0.26473218598403037
  lightness: 0.031514749862253666
  saturation: 0.18730687745846808
  rhythmicContrast: 0.057172088883817196
  brandColors:
    - '#FCFFF5'
    - '#D1DBBD'
    - '#91AA9D'
    - '#3E606F'
    - '#193441'
typography_spectrum: 0.1621379256248474
