layout_spectrum: 0.8275334909558296
name: MadeByJames
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
color:
  brandStrength: 0.676161739975214
  lightness: 0.09975641500204802
  saturation: 0.6190963943954557
  rhythmicContrast: 0.3075627645011991
  brandColors:
    - '#E8E595'
    - '#D0A825'
    - '#40627C'
    - '#26393D'
    - '#FFFAE4'
typography_spectrum: 0.5853373832069337
