layout_spectrum: 1
name: MadeByJames
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 0.5382979
color:
  brandStrength: 1
  lightness: 0.7191489
  saturation: 1
  rhythmicContrast: 1
  brandColors:
    - '#FFFEC2'
    - '#160313'
    - '#753969'
    - '#FF8D7F'
    - '#B10101'
