layout_spectrum: 0.8275334909558296
name: MadeByJames
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
color:
  brandStrength: 0.14006937737576663
  lightness: 0.5211449596099555
  saturation: 0.07415151409804821
  rhythmicContrast: 0.9318581761326641
  brandColors:
    - '#10222B'
    - '#95AB63'
    - '#BDD684'
    - '#E2F0D6'
    - '#F6FFE0'
typography_spectrum: 0.24449763726443052
navigation:
  - name: '#Herbie'
    id: 338d275a-b1d4-4316-959e-6181a706268a
    type: content
